# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1d\n\x0c\x41uthResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"O\n\x12ValidationResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0b\n\x03sub\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"3\n\x0f\x44\x65stroyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbe\x01\n\x0b\x41uthService\x12\x35\n\x0c\x41uthenticate\x12\x11.auth.AuthRequest\x1a\x12.auth.AuthResponse\x12=\n\rValidateToken\x12\x12.auth.TokenRequest\x1a\x18.auth.ValidationResponse\x12\x39\n\x0c\x44\x65stroyToken\x12\x12.auth.TokenRequest\x1a\x15.auth.DestroyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=20
  _globals['_AUTHREQUEST']._serialized_end=69
  _globals['_AUTHRESPONSE']._serialized_start=71
  _globals['_AUTHRESPONSE']._serialized_end=100
  _globals['_TOKENREQUEST']._serialized_start=102
  _globals['_TOKENREQUEST']._serialized_end=131
  _globals['_VALIDATIONRESPONSE']._serialized_start=133
  _globals['_VALIDATIONRESPONSE']._serialized_end=212
  _globals['_DESTROYRESPONSE']._serialized_start=214
  _globals['_DESTROYRESPONSE']._serialized_end=265
  _globals['_AUTHSERVICE']._serialized_start=268
  _globals['_AUTHSERVICE']._serialized_end=458
# @@protoc_insertion_point(module_scope)
