version: '3.8'

services:

  database_m3: 
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
      
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - academia_network

  auth_service:
    build:
      context: ./app
    ports: 
      - "50051:50051"
    networks:
      - academia_network
    depends_on:
      - database_m3
    image: auth_service


  web:
    build: 
      context: ./app
    ports:
      - "8002:8002"
    depends_on:
      - auth_service
    networks:
      - academia_network

volumes:
  postgres_data:

networks:
  academia_network:
    external: true
